3 get/api/topics
aDiallo21/nc-news-project pull request #2
Opened 2022-09-05 15:13 UTC by aDiallo21

GET all topics

2022-09-05 15:29 UTC, leekli requested changes
Well done so far, it's not quite ready to merge though, please review the comments I have left. Once complete please re-submit your PR tomorrow (not today as the deadline has passed). To confirm - do not merge until the changes have been actioned. Thanks.

2022-09-05 15:29 UTC, leekli commented on app.js
> +  console.log(err, "<--- ERROR");
Please remove this console log

2022-09-05 15:29 UTC, leekli commented on models/topics.model.js
> +  return db.query("SELECT * FROM topics").then((topics) => {
Don't forget to end any SQL statements with a semi-colon (;), although PSQL will deal with this for you, it's good practice to keep them in, as it may confuse PSQL with any future more complex queries which you make.

2022-09-05 15:29 UTC, leekli commented on package.json
> +    "express": "^4.18.1",
Express needs to be a main dependency, otherwise the app won't work if express is not installed, please reinstall it not as a dev dependency.

2022-09-06 10:00 UTC, yangalexyangg approved these changes
Looks good Abdoulaye :)

2022-09-06 11:06 UTC, merged